version: "3"

services:
  # Services > Databases
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./services/postgres/.data:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      - app-network

  # Services > Storage
  minio:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - ./services/minio/.data:/data
    networks:
      - app-network
    command: minio server /data

  # Services > Email
  maildev:
    networks:
      - app-network
    image: maildev/maildev

  # Application > My Expenses
  my_expenses:
    command: /bin/sh -c "while sleep 1000; do :; done"
    build:
      context: .
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: neru_core_dev
      PGPORT: 5432
      PGHOST: db
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - minio
      - maildev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres: null
