name: CI

on:
  push:
    branches: [ci, main, staging]
  pull_request:
    branches: [ci, main, staging]

env:
  MIX_ENV: test

jobs:
  deps:
    name: deps
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: ['1.11']
        otp: ['23.2']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Setup
        uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Install deps
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile

  # static_code_analysis:
  #   name: Code Analysis
  #   needs: deps
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       elixir: ['1.11']
  #       otp: ['23.2']
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
        
  #     - name: Setup
  #       uses: actions/setup-elixir@v1
  #       with:
  #         elixir-version: ${{ matrix.elixir }}
  #         otp-version: ${{ matrix.otp }}
      
  #     - name: Check Code Format
  #       run: mix format --check-formatted

  #     - name: Run Credo
  #       run: mix credo --strict --ignore refactor

  # unit_tests:
    name: Unit Tests
    needs: deps
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        otp: ['23.0.0']
        elixir: ['1.11.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Setup
        uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      
      - name: Run tests
        run: mix test --slowest 10