name: CI

on:
  push:
    branches: [ci, main, staging]
  pull_request:
    branches: [ci, main, staging]

env:
  MIX_ENV: test


jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['22.2.7']
        elixir: ['1.11']

    services:
      db:
        image: postgres
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup elixir
        uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Install Mix Dependencies
        if: steps.deps-cache.outputs.cache-hit != 'true' #impedirá a execução dos comandos se houver uma entrada de cache correspondente
        run: mix deps.get
 
      - name: Run Check Formatting #verifica a formatação dos arquivos no projeto
        run: mix format --check-formatted

      - name: Run Credo #ferramenta de linting para Elixir, --strict, pois também mostra oportunidades de refatoração
        run: mix credo --strict --ignore refactor
      
      - name: Run Coveralls #verifica estatísticas de cobertura de teste
        run: mix coveralls          

  # deps:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       otp: ['22.2.7']
  #       elixir: ['1.11']

   
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
        
  #     - name: Setup
  #       uses: erlef/setup-elixir@v1
  #       with:
  #         otp-version: ${{ matrix.otp }}
  #         elixir-version: ${{ matrix.elixir }}

  #     - name: Install deps
  #       run: |
  #         mix local.rebar --force
  #         mix local.hex --force
  #         mix deps.get
  #         mix deps.compile

  # static_code_analysis:
  #   name: Code Analysis
  #   needs: deps
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       otp: ['22.2.7']
  #       elixir: ['1.11']
  #   steps:
  #     - uses: actions/checkout@v2
        
  #     - name: Setup elixir
  #       uses: erlef/setup-elixir@v1
  #       with:
  #         otp-version: ${{ matrix.otp }}
  #         elixir-version: ${{ matrix.elixir }}
      
  #     - name: Check Code Format
  #       run: mix format --check-formatted

  #     - name: Run Credo
  #       run: mix credo --strict --ignore refactor

  # unit_tests:
    # name: Unit Tests
    # needs: deps
    # runs-on: ubuntu-latest
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     otp: ['23.0.0']
    #     elixir: ['1.11.4']
    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v2
    #     with:
    #       fetch-depth: 0
        
    #   - name: Setup
    #     uses: actions/setup-elixir@v1
    #     with:
    #       elixir-version: ${{ matrix.elixir }}
    #       otp-version: ${{ matrix.otp }}
      
    #   - name: Run tests
    #     run: mix test --slowest 10